export const SERVICE_SOURCE = {
  MODEL: 'model',
  FILE: 'file'
}

export const SERVICE_ERROR_CODE = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  SCENARIO_REQUEST_FAILED: 'SCENARIO_REQUEST_FAILED',
  ROUTE_REQUEST_FAILED: 'ROUTE_REQUEST_FAILED',
  ADVISOR_REQUEST_FAILED: 'ADVISOR_REQUEST_FAILED',
  REPORT_REQUEST_FAILED: 'REPORT_REQUEST_FAILED',
  FILE_EXTRACTION_FAILED: 'FILE_EXTRACTION_FAILED'
}

export const SERVICE_META_KEY = {
  SOURCE: 'source',
  MODE: 'mode',
  MODE_LABEL: 'modeLabel',
  COUNT: 'count',
  EXTRACTION_MODE: 'extractionMode'
}
